services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_users
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: VERYSTRONGPASSWORD
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
    container_name: chatbot_app
    ports:
      - "3000:3000"
    environment:
      CONNECTION_STRING: mongodb://root:VERYSTRONGPASSWORD@mongodb_users:27017
      API_KEY_EXA: ${EXA_API_KEY}
      API_KEY_NINJA: ${NINJA_API_KEY}
    depends_on:
      - mongodb

volumes:
  mongo_data:
